### ISSUE TITLE
aggregating across multiple hotspots incorrectly computes sum instead of weighted average

### ISSUE THREAD

**Issue by smoly** [smoly/bubo#1]
- call to nearby_barcharts
- error in barcharts
- here: https://github.com/smoly/bubo/blob/ef58afb4640fa0bdfe313bfb98aefd19597054fc/api/api/ebird.py#L108
- multiply frac by total before agg, then recompute frac

**Comment by jdanbrown** [comment]
Can you add a repro?

**Comment by smoly** [comment]
When I do
```R
nearby_bars <- jsonlite::fromJSON(rawToChar(
  httr::GET(paste0("http://104.197.235.14/nearby_barcharts?lonlat=-120.233466,39.197157&num_nearby_hotspots=10"))[["content"]]))
```

I get the `present_checklist_frac`>2 for Mountain Chickadee:
![image](https://user-images.githubusercontent.com/2320606/34450709-ee8f5766-ecde-11e7-9275-c54ba118ac59.png)

**Comment by jdanbrown** [comment]
Repro confirmed:

![image](https://user-images.githubusercontent.com/627486/34450903-20f1547c-ecdd-11e7-84ea-7965a55c6413.png)

**Comment by jdanbrown** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/627486/34451034-909231c8-ecdf-11e7-8b16-f24a95ffc27f.png)

**Comment by smoly** [comment]
🔥🔥🌈🌈

**Comment by jdanbrown** [comment]
(Fixed in https://github.com/smoly/bubo/commit/c8390fadef8e9cec193e0b750c16206e27c28916)
